### ISSUE TITLE
Doesn't work in Visual studio 2019

### ISSUE THREAD

**Issue by topletal** [Jaex/ImageVisualizer#10]
Hello, 
with the release of Visual Studio 2019 I tried to use ImageVisualizer, however there is an error and the visualizer doesn't work. Unblocked after download, and working as expected in VS 2017. If it would be possible to update it for 2019, I would very much appreacite it, it's one of my most used features in visual studio.
Thanks!

**Comment by Jaex** [comment]
I also have Visual Studio 2019 installed. Downloaded, unblocked and copied ImageVisualizer.dll to Visualizers folder and it worked fine:

![](https://jaex.getsharex.com/2019/04/PaintDotNet_Qj9LpuJdQ0.png)

What is error message?

**Comment by topletal** [comment]
It just shows this: 

![Capture](https://user-images.githubusercontent.com/2494724/56024339-fff0c900-5d39-11e9-8c2c-ccc56b12a3a9.PNG)

**Comment by topletal** [comment]
So I thought its just generic error due to new version, however I googled it, and there was stackoverflow response, that helped me fix it. 

Go to Tools->options->Debugging- Uncheck "Use Managed Compatibility Mode"

Works now.
