### ISSUE TITLE
Not loading properly on VS2015

### ISSUE THREAD

**Issue by studiosi** [Jaex/ImageVisualizer#2]
I installed it today, by downloading the DLL and copying it to the directory that is told in the instructions. Then restarted and got the next error when clicking the "magnifying glass" icon that used to allow me to see the bitmap.

> Unable to load the custom visualizer.
> 
> Could not load file or assembly 'ImageVisualizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

VS Version: 14.0.25123.00 Update 2

**Comment by Jaex** [comment]
Can you try this: http://stackoverflow.com/a/21770848/264877

**Comment by studiosi** [comment]
Yes, unblocking it fixes the issue. Thanks!

**Comment by Jaex** [comment]
Updated readme to contain info about it.
