### ISSUE TITLE
Doesn't support Visual Studio 2013

### ISSUE THREAD

**Issue by JayWang0** [Jaex/ImageVisualizer#3]
Doesn't support Visual Studio 2013

**Comment by Jaex** [comment]
When I first made this, it was for VS2013. So it must work for 2013 too. Are you sure you copying dll to correct place? I can't test it myself because not planning to install previous version of Visual Studio.

**Comment by Congee** [comment]
Hey buddy, I'm using Visual Studio 2015, it just doesn't work.
The popup messagebox says:

```
Unable to load the custom visualizer.

**Aditional Information:**
Could not load file or assembly 'ImageVisualizer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
```

**Comment by Jaex** [comment]
@Congee that error happens when you didn't unblock downloaded dll file.

Check instructions here: https://github.com/Jaex/ImageVisualizer#option-1-download-it

**Comment by Jaex** [comment]
#2

**Comment by Congee** [comment]
It works like a charm! Thanks a lot, and sorry for being impatient.
