### ISSUE TITLE
ESC key and Save Image, almost ok

### ISSUE THREAD

**Issue by ilMes** [Jaex/ImageVisualizer#5]
When open the "Save Image ..." button and cancel by pressing ESC key, all app will close.

**Comment by Jaex** [comment]
That means ESC key closes save dialog on "key down" but main window closes on "key up". Reason why I used "key up" event is so when you close main window with ESC key then Visual Studio won't receive ESC key up event.

**Comment by ilMes** [comment]
- Can the use of Click event intead of KeuUp resolve this situation?
- Can remove/readd the KeyUp event handler in Save Image resolve this situation?
