### ISSUE TITLE
ToolTip on new GitHob button

### ISSUE THREAD

**Issue by ilMes** [Jaex/ImageVisualizer#6]
A cute thing is to add a **tooltip** on new GitHub button

**Comment by Jaex** [comment]
I wanted to add tooltip to it but when I enabled tooltips on ToolStrip then all buttons have tooltips even those which have text. Therefore I couldn't add tooltip only to GitHub button.

**Comment by ilMes** [comment]
- a work around can be to use two distinct toolbar docked into a panel, DockFull for the left toolbar, DockRight for the GitHub toolbar

**Comment by Jaex** [comment]
That workaround is not good enough, it will look as two different toolbar. But found a way now.
