### ISSUE TITLE
Error: Unable to load the custom visualizer.

### ISSUE THREAD

**Issue by EchterAgo** [Jaex/ImageVisualizer#7]
Additional information:

The UI-side visualizer type 'ImageVisualizer.ImageVisualizer' must derive from 'Microsoft.VisualStudio.DebuggerVisualizers.DialogDebuggerVisualizer'.

Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.12) Release
VisualStudio.15.Release/15.2.0+26430.12
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Professional

Visual Basic 2017   00370-10000-00000-AA254
Microsoft Visual Basic 2017

Visual C# 2017   00370-10000-00000-AA254
Microsoft Visual C# 2017

Visual C++ 2017   00370-10000-00000-AA254
Microsoft Visual C++ 2017

Arduino for Visual Studio   1.0
Arduino extension for Visual Studio. For more information please see docs, faq and forum at http://www.visualmicro.com

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

EditorConfig Language Service   1.17.202
Language service for .editorconfig files.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Markdown Editor   1.11.214
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

MenuCommands Extension   1.0
MenuCommands Visual Studio Extension Detailed Info

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Rebracer   1.0
Saves editor formatting settings as part of each solution.

ResXManager   1.1.424.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.26430.06
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by EchterAgo** [comment]
Nevermind, building the extension from git master worked for me. Seems like it was fixed in master but no release was made since then.

**Comment by Jaex** [comment]
Released new build which supports Visual Studio 2017 now.
